## Important Resources which covers most numpy concepts: https://www.tutorialspoint.com/numpy/index.htm

In [ ]:
import numpy as np

# Creating Arrays

* All elements in numpy array must be same datatype that way it takes less space in memory. If varying datatypes are there in a list then it is converted to highest level data type.

* For Example: `l = ['abc', 1, True, 2.50, [1,2,3]]`

* `np.array(l)` will have `str` data type as it is highest level data type in above list.

* Order of highest to lowest data type: `str > float > int > bool`



## Create 1-D Array

In [ ]:
one_d_arr = np.array([1,2,3])
print(one_d_arr)
print(one_d_arr.shape)

[1 2 3]
(3,)


## Create 2-D Array

In [ ]:
two_d_arr = np.array([[1,2,3], [4,5,6]])
print(two_d_arr)
print(two_d_arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


 ## Create 3-D Array

In [ ]:
three_d_arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(three_d_arr)
print(three_d_arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


## Creating array from scratch using Functions

### Create array with Zeros


In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Create Array with Random Values

In [ ]:
np.random.random((5,2))

array([[0.62981221, 0.03323481],
       [0.5548516 , 0.52059144],
       [0.65805041, 0.91083283],
       [0.10583742, 0.3787707 ],
       [0.47101046, 0.71477554]])

### Create Array with arange function

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(0,5,2)

array([0, 2, 4])

# Shape of Array

In [ ]:
one_d_arr.shape

(3,)

In [ ]:
three_d_arr.shape

(2, 2, 3)

# Flatten Method


In [ ]:
two_d_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# concatenates the rows at the end of previous row
two_d_arr.flatten(order='C')

array([1, 2, 3, 4, 5, 6])

In [ ]:
# concatenates
two_d_arr.flatten(order='F')

array([1, 4, 2, 5, 3, 6])

#Reshape method

In [ ]:
two_d_arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

# Numpy Data Types

* Numpy has very specific datatypes for `int` and `float`.

* `np.int32, np.int64, np.float32, np.float64`

## Check data type

In [ ]:
one_d_arr.dtype

dtype('int64')

In [ ]:
np.array(['hello']).dtype

dtype('<U5')

## Setting Data type while creation

In [ ]:
np.array([1.5, 2.6], dtype=np.float64).dtype

dtype('float64')

## Setting data type after creation

In [ ]:
np.array([True, 23.23, 1, "Hello"]).astype('<U4')

array(['True', '23.2', '1', 'Hell'], dtype='<U4')